[tool.flake8]
max-line-length = 88
min_python_version = 3.8

[tool.blue]
line-length = 88

[tool.isort]
profile = "black"
known_third_party = ["ansible"]
add_imports = ["from __future__ import annotations"]

[tool.mypy]
mypy_path = "stubs"
allow_redefinition = false
check_untyped_defs = true
ignore_errors = false
ignore_missing_imports = true
implicit_reexport = false
local_partial_types = true
strict_optional = true
strict_equality = true
no_implicit_optional = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unreachable = true
warn_no_return = true

[tool.pyright]
pythonVersion = "3.8"
#typeCheckingMode = "strict"
venvPath = "."
venv = "venv"
stubPath = "stubs"
